#!/bin/sh

# Copyright © 2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

pid=$(pgrep -x Xorg)
grep -o -E '[^/]+_drv[.]so$' "/proc/$pid/maps" | sort -u

# vim:ts=4 sts=4 sw=4 et
