#!/bin/sh

# Copyright © 2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -ne 3 ]
then
    printf 'Usage: %s OUTPUT WIDTH HEIGHT\n' "${0#**/}" >&2
    exit 1
fi
output="$1"
x=$(($2))
y=$(($3))
name="${x}x${y}"
cvt=$(cvt "$x" "$y")
while read -r _key _ _mode
do
    if [ "$_key" = 'Modeline' ]
    then
        mode="$_mode"
        break
    fi
done <<EOF
$cvt
EOF
xrandr --newmode "$name" $mode
xrandr --addmode "$output" "$name"

# vim:ts=4 sts=4 sw=4 et
